package com.thh.kiosk.queue.modules.setting;

public enum SettingKey {
    KIOSK_TITLE,
    LOGO_URL,

    CUSTOMER_COLOR_PRIMARY,
    CUSTOMER_COLOR_SECONDARY,
    CUSTOMER_COLOR_BACKGROUND,
    CUSTOMER_COLOR_TEXT_HIGHLIGHT,

    VIEWER_COLOR_PRIMARY,
    VIEWER_COLOR_SECONDARY,
    VIEWER_COLOR_BACKGROUND,
    VIEWER_COLOR_TEXT_HIGHLIGHT
}
